apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubext-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
- apiGroups:
  - jbrette.io
  resources:
  - manageds
  verbs:
  - get
  - list
  - watch
  - update
  - patch
