// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/jbrette/kubext/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Manageds returns a ManagedInformer.
	Manageds() ManagedInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Manageds returns a ManagedInformer.
func (v *version) Manageds() ManagedInformer {
	return &managedInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
