// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	managed_v1alpha1 "github.com/jbrette/kubext/pkg/apis/managed/v1alpha1"
	versioned "github.com/jbrette/kubext/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jbrette/kubext/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jbrette/kubext/pkg/client/listers/managed/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManagedInformer provides access to a shared informer and lister for
// Manageds.
type ManagedInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ManagedLister
}

type managedInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManagedInformer constructs a new informer for Managed type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManagedInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManagedInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManagedInformer constructs a new informer for Managed type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManagedInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArgoprojV1alpha1().Manageds(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArgoprojV1alpha1().Manageds(namespace).Watch(options)
			},
		},
		&managed_v1alpha1.Managed{},
		resyncPeriod,
		indexers,
	)
}

func (f *managedInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManagedInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *managedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&managed_v1alpha1.Managed{}, f.defaultInformer)
}

func (f *managedInformer) Lister() v1alpha1.ManagedLister {
	return v1alpha1.NewManagedLister(f.Informer().GetIndexer())
}
