// This file was automatically generated by lister-gen

package v1alpha1

// ManagedListerExpansion allows custom methods to be added to
// ManagedLister.
type ManagedListerExpansion interface{}

// ManagedNamespaceListerExpansion allows custom methods to be added to
// ManagedNamespaceLister.
type ManagedNamespaceListerExpansion interface{}
